### ISSUE TITLE
Error when adding a new site

### ISSUE THREAD

**Issue by pixelmachine** [verbb/gift-voucher#124]
### Describe the bug

I've just added a new site to my multi-site install and received the following error which I think is due to Gift Voucher:

```
yii\base\UnknownMethodException: Calling unknown method: craft\services\ProjectConfig::getIsApplyingYamlChanges() in /var/www/html/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /var/www/html/vendor/verbb/gift-voucher/src/services/VoucherTypes.php(441): yii\base\Component->__call('getIsApplyingYa...', Array)
#1 [internal function]: verbb\giftvoucher\services\VoucherTypes->afterSaveSiteHandler(Object(craft\events\SiteEvent))
#2 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\events\SiteEvent))
#3 /var/www/html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'afterSaveSite', Object(craft\events\SiteEvent))
#4 /var/www/html/vendor/craftcms/cms/src/services/Sites.php(811): yii\base\Component->trigger('afterSaveSite', Object(craft\events\SiteEvent))
#5 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1850): craft\services\Sites->handleChangedSite(Object(craft\events\ConfigEvent))
#6 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1143): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#7 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#8 /var/www/html/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#9 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(82): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#10 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(530): craft\models\ProjectConfigData->commitChanges(NULL, Array, 'sites.552205fa-...', true, 'Save the \xE2\x80\x9Csko...', true)
#11 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(490): craft\services\ProjectConfig->_setInternal('sites.552205fa-...', Array, 'Save the \xE2\x80\x9Csko...', true, false)
#12 /var/www/html/vendor/craftcms/cms/src/services/Sites.php(680): craft\services\ProjectConfig->set('sites.552205fa-...', Array, 'Save the \xE2\x80\x9Csko...')
#13 /var/www/html/vendor/craftcms/cms/src/controllers/SitesController.php(329): craft\services\Sites->saveSite(Object(craft\models\Site))
#14 [internal function]: craft\controllers\SitesController->actionSaveSite()
#15 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#17 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-site', Array)
#18 /var/www/html/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->runAction('sites/save-site', Array)
#19 /var/www/html/vendor/craftcms/cms/src/web/Application.php(642): craft\web\Application->runAction('sites/save-site', Array)
#20 /var/www/html/vendor/craftcms/cms/src/web/Application.php(303): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#21 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /var/www/html/web/index.php(12): yii\base\Application->run()
#23 {main}
```

Not sure if it's related but I have the config `writeYamlAutomatically` set to false.

### Steps to reproduce

1. Disable project config writing
2. Add a new site

### Craft CMS version

4.8.4

### Plugin version

3.0.12

### Multi-site?

Yes

**Comment by pixelmachine** [comment]
Also got the following when rebuilding the config:

```
$ craft project-config/rebuild
Rebuilding the project config from the current state ... error: Tried to save a voucher type that is missing site settings
Failed to run craft project-config/rebuild: exit status 1
```
Went away after manually saving each type

**Comment by pixelmachine** [comment]
I've just spotted that this has been addressed in the 4 beta.
