### ISSUE TITLE
Setting read-only property: craft\commerce\models\LineItem::salePrice in Craft Commerce 5

### ISSUE THREAD

**Issue by sunscreem** [verbb/gift-voucher#130]
### Describe the bug

Adding a voucher to the cart with a custom amount in Craft Commerce 5 throws

```
Setting read-only property: craft\commerce\models\LineItem::salePrice
```

### Steps to reproduce

1.  Clean install latest versions of Craft, Commerce and Gift Voucher
2. Create a gift voucher with custom amount
3. Add front end template and try to add to cart.

### Craft CMS version

5.2.8

### Plugin version

4.0.1

### Multi-site?

No

### Additional context

Commerce 5.0.13 also installed.

**Comment by engram-design** [comment]
Fixed in [4.0.2](https://github.com/verbb/gift-voucher/releases/tag/4.0.2)

**Comment by maxpdesign** [comment]
I am getting the same error when I use the `craft.giftVoucher.getPdfUrl(item)` on the completed order page

**Comment by engram-design** [comment]
@maxpdesign Not able to replicate that sorry. Can you share the full stack trace of the error so I can see where it's coming from?

**Comment by maxpdesign** [comment]
@engram-design I am experiencing this on 2 websites now, exact same error. I am looping over the line items of a completed order, checking if it's a voucher and then displaying a PDF download link with `{{ craft.giftVoucher.getPdfUrl(item) }}` (where "item" is a lineItem). When I click the download link I am getting the error below.

---

yii\base\InvalidCallException: Setting read-only property: craft\commerce\models\LineItem::salePrice in /var/www/html/vendor/yiisoft/yii2/base/Component.php:218
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/helpers/App.php(1539): yii\base\Component->__set('salePrice', '50.0000')
#1 /var/www/html/vendor/craftcms/cms/src/base/Model.php(81): craft\helpers\App::configure(Object(craft\commerce\models\LineItem), Array)
#2 /var/www/html/vendor/verbb/gift-voucher/src/controllers/DownloadsController.php(127): craft\base\Model->__construct(Array)
#3 /var/www/html/vendor/verbb/gift-voucher/src/controllers/DownloadsController.php(64): verbb\giftvoucher\controllers\DownloadsController->_getLineItemByUid('ad18023f-2ed0-4...')
#4 [internal function]: verbb\giftvoucher\controllers\DownloadsController->actionPdf()
#5 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#7 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('pdf', Array)
#8 /var/www/html/vendor/craftcms/cms/src/web/Application.php(361): yii\base\Module->runAction('gift-voucher/do...', Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/Application.php(660): craft\web\Application->runAction('gift-voucher/do...', Array)
#10 /var/www/html/vendor/craftcms/cms/src/web/Application.php(323): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#11 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /var/www/html/www/index.php(12): yii\base\Application->run()
#13 {main}

**Comment by engram-design** [comment]
Ah, thanks for that. Fixed for the next release. To get this early, run `composer require verbb/gift-voucher:"dev-craft-5 as 4.0.2"`.

**Comment by engram-design** [comment]
Updated in [4.0.3](https://github.com/verbb/gift-voucher/releases/tag/4.0.3).
