### ISSUE TITLE
Error rending pdf on order complete

### ISSUE THREAD

**Issue by mikeymeister** [verbb/gift-voucher#66]
**Description**
My Gift Voucher Pdfs attached to order emails are failing to render when sent as an attachment on order complete. Pdf's render correctly when using a download link on the front end and when using the resend email feature from an order detail page in commerce.

The following error exists in queue.log:
```2021-04-30 16:55:55 [-][11][-][error][gift-voucher] An error occurred while generating this PDF: An exception has been thrown during the rendering of a template ("session_set_cookie_params(): Cannot change session cookie parameters when headers already sent") in "_routers/pdf".
2021-04-30 16:55:55 [-][11][-][error][gift-voucher] Voucher PDF render error. Order number: ae5fc17. An exception has been thrown during the rendering of a template ("session_set_cookie_params(): Cannot change session cookie parameters when headers already sent") in "_routers/pdf".
2021-04-30 16:55:55 [-][11][-][error][gift-voucher] Voucher PDF render error. Code key: 2N32UMZCQV. An exception has been thrown during the rendering of a template ("session_set_cookie_params(): Cannot change session cookie parameters when headers already sent") in "_routers/pdf".
2021-04-30 16:55:55 [-][11][-][error][Twig\Error\RuntimeError] yii\base\ErrorException: session_set_cookie_params(): Cannot change session cookie parameters when headers already sent in /app/vendor/yiisoft/yii2/web/Session.php:432
Stack trace:
#0 {main}

Next Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("session_set_cookie_params(): Cannot change session cookie parameters when headers already sent") in "_routers/pdf". in /app/vendor/twig/twig/src/Template.php:419
Stack trace:
#0 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#1 /app/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#2 /app/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#3 /app/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#4 /app/vendor/craftcms/cms/src/web/View.php(390): Twig\Environment->render('_routers/pdf', Array)
#5 /app/vendor/verbb/gift-voucher/src/services/PdfService.php(129): craft\web\View->renderTemplate('_routers/pdf', Array)
#6 /app/vendor/verbb/gift-voucher/src/services/VouchersService.php(84): verbb\giftvoucher\services\PdfService->renderPdf(Array, Object(craft\commerce\elements\Order), NULL, NULL)
#7 [internal function]: verbb\giftvoucher\services\VouchersService->onBeforeSendEmail(Object(craft\commerce\events\MailEvent))
#8 /app/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\commerce\events\MailEvent))
#9 /app/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('craft\\commerce\\...', 'beforeSendEmail', Object(craft\commerce\events\MailEvent))
#10 /app/vendor/craftcms/commerce/src/services/Emails.php(791): yii\base\Component->trigger('beforeSendEmail', Object(craft\commerce\events\MailEvent))
#11 /app/vendor/craftcms/commerce/src/queue/jobs/SendEmail.php(54): craft\commerce\services\Emails->sendEmail(Object(craft\commerce\models\Email), Object(craft\commerce\elements\Order), Object(craft\commerce\models\OrderHistory), Array, '')
#12 /app/vendor/yiisoft/yii2-queue/src/Queue.php(246): craft\commerce\queue\jobs\SendEmail->execute(Object(craft\queue\Queue))
#13 /app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('95', 'O:35:"craft\\com...', '300', 1)
#14 /app/vendor/craftcms/cms/src/queue/Queue.php(131): yii\queue\cli\Queue->handleMessage('95', 'O:35:"craft\\com...', '300', 1)
#15 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#16 /app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#17 /app/vendor/craftcms/cms/src/queue/Queue.php(140): yii\queue\cli\Queue->runWorker(Object(Closure))
#18 /app/vendor/craftcms/cms/src/controllers/QueueController.php(84): craft\queue\Queue->run()
#19 [internal function]: craft\controllers\QueueController->actionRun()
#20 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#22 /app/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('run', Array)
#23 /app/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('run', Array)
#24 /app/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('queue/run', Array)
#25 /app/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('queue/run', Array)
#26 /app/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#27 /app/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#28 /app/public/index.php(21): yii\base\Application->run()
#29 {main}
```

**Steps to reproduce**
1. Set up commerce email to send on order complete.
2. Set up gift voucher settings to attach gift voucher to that email.
3. Complete order containing gift voucher through the front end.
4. Check the sent email attachment.
5. Download gift voucher pdf through another means to check for successful render.

**Additional info**
- Plugin version: 2.5.9
- Craft version: 3.6.12
- Craft Commerce version: 3.3.0.1
- Multi-site: No

**Additional context**
I might have set something up incorrectly so any help would be appreciated. The template mentioned in the log "_routers/pdf" simply contains some logic to decide which voucher designs are required and then uses {% include %} to render them.

**Comment by engram-design** [comment]
Hard to say, can you post the content of your `_routers/pdf` file, and potential the content of the template file you're including?

As a first-test, I'd strip the template back to "Test" as being the sole content, just to test out first. If that works, then I'd say its something in your template causing this issue, and would advise trial-and-error removing things.

What is your Craft queue processing set to? Are you using the command line, or a daemon to process the queue? I ask as this is the only real difference between sending emails from the control panel and "normal" orders. However, I have tested both without issue (running queue via CLI, and running via CP).

**Comment by mikeymeister** [comment]
Thanks for the quick reply. For reasons that must have made sense to me at the time it was written, I had the line `{% set cart = craft.commerce.carts.cart %}` in the router template. Removing that stopped the error, which makes sense. I should have seen that sooner, so apologies but thanks for your help.
