### ISSUE TITLE
Calling unknown method: craft\models\FieldLayoutTab::getFields()

### ISSUE THREAD

**Issue by CMeldgaard** [verbb/gift-voucher#99]
### Describe the bug

When saving af a new vucher code, where there is relation fields in the basedata. If none is filled out, we get the error

```yii\base\UnknownMethodException: Calling unknown method: craft\models\FieldLayoutTab::getFields() in /app/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /app/vendor/verbb/gift-voucher/src/controllers/CodesController.php(65): yii\base\Component->__call('getFields', Array)
#1 [internal function]: verbb\giftvoucher\controllers\CodesController->actionEdit(NULL, Object(verbb\giftvoucher\elements\Code))
#2 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#4 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('edit', Array)
#5 /app/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('gift-voucher/co...', Array)
#6 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('gift-voucher/co...', Array)
#7 /app/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /app/web/index.php(29): yii\base\Application->run()
#10 {main}```

### Steps to reproduce

1. Create a basedata fields which has multiple relations fields
2. Create a voucher code, but without setting any of the relations fields
3. Save the new voucher code
4. Get error: Calling unknown method: craft\models\FieldLayoutTab::getFields()

If i add an relation to any of the relations fields, then the error doesnt occour

### Craft CMS version

4.3.1

### Plugin version

3.0.2

### Multi-site?

No

### Additional context

_No response_

**Comment by engram-design** [comment]
Fixed in [3.0.3](https://github.com/verbb/gift-voucher/releases/tag/3.0.3)
